/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.edu.utp.sistemaropa.vista;

import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import pe.edu.utp.sistemaropa.DaoImpl.ProductoDaoImpl;
import pe.edu.utp.sistemaropa.config.Conexion;
import pe.edu.utp.sistemaropa.dto.Producto;

/**
 *
 * @author Nayely
 */
public class ManejoProductosJFrame extends javax.swing.JFrame {

   Producto prod = new Producto();
    ProductoDaoImpl prodDao = new ProductoDaoImpl();
    DefaultTableModel modelo = new DefaultTableModel();

    private PreparedStatement ps;
    private ResultSet rs;
    private Connection conex;
FondoPanel fondo = new FondoPanel();
    public ManejoProductosJFrame() {
        this.setContentPane(fondo);
        initComponents();
        this.cbxProv.setModel(obtenerProducto());
        ListarProducto();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNombProd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPrecioProd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStockProd = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnNuevoTipoPago2 = new javax.swing.JButton();
        btnGuardarTipoPago2 = new javax.swing.JButton();
        btnEditarTipoPago2 = new javax.swing.JButton();
        btnEliminarTipoPago2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        btnSalirTipoPago3 = new javax.swing.JButton();
        cbxProv = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Ink Free", 1, 48)); // NOI18N
        jLabel6.setText("Manejo de Productos");

        txtNombProd.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtNombProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombProdActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel2.setText("NOMBRE");

        jLabel3.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel3.setText("PRECIO");

        txtPrecioProd.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        txtPrecioProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioProdActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel4.setText("STOCK");

        txtStockProd.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setOpaque(false);

        btnNuevoTipoPago2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/sistemaropa/img/añadir1.png"))); // NOI18N
        btnNuevoTipoPago2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoTipoPago2ActionPerformed(evt);
            }
        });

        btnGuardarTipoPago2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/sistemaropa/img/Guard.png"))); // NOI18N
        btnGuardarTipoPago2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTipoPago2ActionPerformed(evt);
            }
        });

        btnEditarTipoPago2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/sistemaropa/img/refresh_.png"))); // NOI18N
        btnEditarTipoPago2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTipoPago2ActionPerformed(evt);
            }
        });

        btnEliminarTipoPago2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/sistemaropa/img/exit.png"))); // NOI18N
        btnEliminarTipoPago2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTipoPago2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevoTipoPago2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarTipoPago2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnEditarTipoPago2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEliminarTipoPago2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoTipoPago2)
                    .addComponent(btnEditarTipoPago2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarTipoPago2)
                    .addComponent(btnEliminarTipoPago2))
                .addGap(23, 23, 23))
        );

        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel1.setText("PROVEEDOR");

        tblProducto.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOMBRE", "PRECIO", "STOCK", "PROVEEDOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProducto.getTableHeader().setReorderingAllowed(false);
        tblProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProducto);

        btnSalirTipoPago3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/sistemaropa/img/regresar.png"))); // NOI18N
        btnSalirTipoPago3.setContentAreaFilled(false);
        btnSalirTipoPago3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirTipoPago3ActionPerformed(evt);
            }
        });

        cbxProv.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        cbxProv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombProd, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtPrecioProd))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtStockProd)
                    .addComponent(cbxProv, 0, 200, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalirTipoPago3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel6)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnSalirTipoPago3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStockProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPrecioProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(cbxProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombProdActionPerformed

    private void txtPrecioProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProdActionPerformed

    private void btnNuevoTipoPago2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoTipoPago2ActionPerformed
        LimpiarDatos();
    }//GEN-LAST:event_btnNuevoTipoPago2ActionPerformed

    private void btnGuardarTipoPago2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTipoPago2ActionPerformed
        crearProducto();
    }//GEN-LAST:event_btnGuardarTipoPago2ActionPerformed

    private void btnEditarTipoPago2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTipoPago2ActionPerformed

            ActualizarProducto();
    }//GEN-LAST:event_btnEditarTipoPago2ActionPerformed

    private void btnEliminarTipoPago2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTipoPago2ActionPerformed
        EliminarProducto();
    }//GEN-LAST:event_btnEliminarTipoPago2ActionPerformed

    private void tblProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductoMouseClicked
        ObtenerDatosTabla();
    }//GEN-LAST:event_tblProductoMouseClicked

    private void btnSalirTipoPago3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirTipoPago3ActionPerformed
         MenuAdministradorJFrame a = new MenuAdministradorJFrame();

        int confirm = JOptionPane.showConfirmDialog(a, "¿Desea salir?", "Confirmación de Salida", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            a.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirTipoPago3ActionPerformed

   public int getIdProveedor(String nombre) {
        int idProve = -1;
        PreparedStatement statement = null;
        ResultSet resultSet = null;

        try {
            String query = "SELECT IdProveedor FROM proveedor WHERE Nombre = ?";
            statement = conex.prepareStatement(query);
            statement.setString(1, nombre); // Asignar el parámetro del nombre del cliente

            resultSet = statement.executeQuery();

            if (resultSet.next()) {
                idProve = resultSet.getInt("IdProveedor");
            }
        } catch (SQLException e) {
            System.out.println("Error al obtener el ID del proveedor: " + e.getMessage());
        }
        return idProve;
    }

    public ResultSet consulta(String sql) {
        rs = null;
        try {
            conex = Conexion.getConexion();
            ps = conex.prepareStatement(sql);
            rs = ps.executeQuery();
        } catch (SQLException e) {
            System.out.println("Error " + e);
        }
        return rs;
    }

    public DefaultComboBoxModel obtenerProducto() {
        DefaultComboBoxModel ListaModelo = new DefaultComboBoxModel();
        ListaModelo.addElement("Seleccionar");
        rs = this.consulta("SELECT Nombre FROM proveedor");
        try {
            while (rs.next()) {
                ListaModelo.addElement(rs.getString("Nombre"));
            }
            rs.close();
        } catch (SQLException e) {
            System.out.println("Error " + e);
        }
        return ListaModelo;
    }

    void crearProducto() {
        String nomprod = txtNombProd.getText();
        String nomStock = txtStockProd.getText();
        String precioprod = txtPrecioProd.getText();
        String prov = cbxProv.getSelectedItem().toString();
        System.out.println("" + prov);

        if (!"Seleccionar".equals(prov)) {
            int ab = this.getIdProveedor(prov);
            double precio = Double.parseDouble(precioprod);
            int Stock = Integer.parseInt(nomStock);

            prod.setNombre(nomprod);
            prod.setPrecio(precio);
            prod.setStock(Stock);
            prod.setIdproveedor(ab);

            prodDao.create(prod);

            LimpiarProducto();
            ListarProducto();
            LimpiarDatos();
            this.cbxProv.setModel(obtenerProducto());
            JOptionPane.showMessageDialog(null, "PRODUCTO REGISTRADO");
        } else {

            JOptionPane.showMessageDialog(null, "SELECCIONE CORRECTAMENTE EL PROVEEDOR");

        }

    }

    void EliminarProducto() {
        modelo = (DefaultTableModel) tblProducto.getModel();
        int selectedRow = tblProducto.getSelectedRow();

        if (selectedRow != -1) {
            int pregunta = JOptionPane.showConfirmDialog(null, "¿ESTAS SEGURO DE ELIMINAR?");
            if (pregunta == JOptionPane.YES_OPTION) {
                int idProd = (int) tblProducto.getValueAt(selectedRow, 0);
                prodDao.delete(idProd);
                LimpiarProducto();
                ListarProducto();
                LimpiarDatos();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona una fila");
        }
    }

    void ActualizarProducto() {
        modelo = (DefaultTableModel) tblProducto.getModel();

        int selectedRow = tblProducto.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "SELECCIONE UNA FILA");
        } else {
            String nomprod = txtNombProd.getText();
            String nomStock = txtStockProd.getText();
            String precioprod = txtPrecioProd.getText();
            String prov = cbxProv.getSelectedItem().toString();

            if (!nomprod.isEmpty() && !nomStock.isEmpty() && !precioprod.isEmpty() && !prov.isEmpty()) {

                int idProd = (int) tblProducto.getValueAt(selectedRow, 0);

                double precio = Double.parseDouble(precioprod);
                int Stock = Integer.parseInt(nomStock);
                int ab = this.getIdProveedor(prov);

                prod.setNombre(nomprod);
                prod.setStock(Stock);
                prod.setPrecio(precio);
                prod.setIdproveedor(ab);
                prod.setIdproducto(idProd);

                prodDao.update(prod);

                LimpiarProducto();
                ListarProducto();
                LimpiarDatos();
                JOptionPane.showMessageDialog(null, "PRODUCTO MODIFICADO");

            } else {
                JOptionPane.showMessageDialog(null, "LOS CAMPOS ESTAN VACIOS");
            }
        }
    }

    void ObtenerDatosTabla() {
        modelo = (DefaultTableModel) tblProducto.getModel();

        int selectedRow = tblProducto.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una fila de la tabla");
        } else {
            String nomprod = modelo.getValueAt(selectedRow, 1).toString();
            String nomStock = modelo.getValueAt(selectedRow, 2).toString();
            String precioprod = modelo.getValueAt(selectedRow, 3).toString();
            String prov = modelo.getValueAt(selectedRow, 4).toString();

            String provee = getNombreProveedorR(prov);

            cbxProv.setSelectedItem(provee);
            txtNombProd.setText(nomprod);
            txtStockProd.setText(nomStock);
            txtPrecioProd.setText(precioprod);

        }
    }

    public String getNombreProveedorR(String nombre) {
        String nombrepro = "";
        PreparedStatement statement = null;
        ResultSet resultSet = null;

        try {
            String query = ("""
                            SELECT Nombre
                            FROM proveedor
                            WHERE IdProveedor = ?""");
            statement = conex.prepareStatement(query);
            statement.setString(1, nombre); // Asignar el parámetro del nombre del cliente

            resultSet = statement.executeQuery();

            if (resultSet.next()) {
                nombrepro = resultSet.getString("nombre");
            }
        } catch (SQLException e) {
            System.out.println("Error al obtener el nombre del proveedor: " + e.getMessage());
        }
        return nombrepro;
    }

    void LimpiarProducto() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    void ListarProducto() {
        DefaultTableModel modelo = (DefaultTableModel) tblProducto.getModel();
        modelo.setRowCount(0);
        modelo.setColumnCount(0);

        modelo.setColumnIdentifiers(new Object[]{"ID Producto", "Nombre", "Stock", "Precio", "ID Proveedor"});

        List<Producto> listar = prodDao.readAll();
        for (Producto producto : listar) {
            Object[] ob = new Object[5];
            ob[0] = producto.getIdproducto();
            ob[1] = producto.getNombre();
            ob[2] = producto.getStock();
            ob[3] = producto.getPrecio();
            ob[4] = producto.getIdproveedor();

            modelo.addRow(ob);
        }
    }

    void LimpiarDatos() {
        txtNombProd.setText("");
        txtStockProd.setText("");
        txtPrecioProd.setText("");
        cbxProv.setSelectedItem("Seleccionar");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManejoProductosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManejoProductosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManejoProductosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManejoProductosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManejoProductosJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarTipoPago2;
    private javax.swing.JButton btnEliminarTipoPago2;
    private javax.swing.JButton btnGuardarTipoPago2;
    private javax.swing.JButton btnNuevoTipoPago2;
    private javax.swing.JButton btnSalirTipoPago3;
    private javax.swing.JComboBox<String> cbxProv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProducto;
    private javax.swing.JTextField txtNombProd;
    private javax.swing.JTextField txtPrecioProd;
    private javax.swing.JTextField txtStockProd;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {
        private Image imagen;

        public FondoPanel() {
            // Cargar la imagen en el constructor del panel
            URL imageURL = getClass().getResource("/pe/edu/utp/sistemaropa/img/fondorosa.png");
            if (imageURL != null) {
                imagen = new ImageIcon(imageURL).getImage();
            } else {
                System.err.println("La imagen no se encuentra en la ruta especificada.");
            }
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (imagen != null) {
                g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            }
        }
    }
}
